#Created by: Corona Pacheco Adrian
#Date: 28/09/2023

CREATE DATABASE IF NOT EXISTS Mineria_db;

USE Mineria_db;

CREATE TABLE IF NOT EXISTS Telefonos(
	id INT NOT NULL AUTO_INCREMENT,
    tel VARCHAR(100),
    PRIMARY KEY (id)
    );

INSERT INTO telefonos(tel)
	VALUES (' POCO F6 pro'),
(' Honor Magic 6 lite'),
(' Motorola edge 50 fusion'),
(' Xiaomi note 13 pro'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi note 13 pro plus'),
(' Honor Magic 6 lite'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi note 13 pro'),
(' Motorola edge 50 fusion'),
(' Xiaomi note 13 pro'),
(' OPPO reno 11'),
(' OPPO reno 11'),
(' OPPO reno 11'),
(' Nothing 2A'),
(' OPPO reno 11'),
(' Nothing 2A'),
(' Xiaomi note 13 pro plus'),
(' Samsung A54'),
(' OPPO reno 11'),
(' Xiaomi 12 Pro'),
(' OPPO reno 11'),
(' Iphone 15 Pro Max'),
(' OPPO reno 11'),
(' Redmagic 9 Pro'),
(' Google Pixel 8A'),
(' Samsung A35'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi 12 pro plus'),
(' Xiaomi note 13 Pro'),
(' Huawei Pura 70'),
(' POCO F6 pro'),
(' Samsung note 20 ultra'),
(' Motorola edge 50 ultra'),
(' Realme 12 proplus'),
(' Infinix note 40 pro'),
(' Xiaomi 13T'),
(' Nothing 2A'),
(' Google Pixel 8A'),
(' Nothing 2A'),
(' Xiaomi 13T pro'),
(' Honor Magic 5 lite'),
(' Xiaomi 13T pro'),
(' Xiaomi 13T pro'),
(' Iphone 15 Plus'),
(' Xiaomi 13T pro'),
(' Iphone 15'),
(' Honor X6'),
(' Samsung S23 Ultra'),
(' Samsung S24 Ultra'),
(' Xiaomi note 13 Pro'),
(' Samsung S23 plus'),
(' Nubia z60 Ultra'),
(' Nothin 2A'),
(' Iphone 15'),
(' POCO X6 pro'),
(' Honor 90'),
(' Iphone 15 plus'),
(' Iphone 15'),
(' Iphone 14 plus'),
(' Iphone 13 pro max'),
(' POCO X6 pro'),
(' Nothing 2A'),
(' Iphone 13 pro'),
(' Iphone 15'),
(' Iphone 15'),
(' Iphone 15'),
(' Iphone 14 pro'),
(' Iphone 14 pro max'),
(' Nothing 2A'),
(' Realme GT3'),
(' Cubot P80'),
(' Iphone 15 plus'),
(' Xiaomi note 13 pro'),
(' Infinix note 40 pro	'),
(' POCO X6 pro'),
(' Xiaomi note 13 pro'),
(' Infinix note 40 pro'),
(' Xiaomi note 13 pro'),
(' Infinix GT 20 pro'),
(' Xiaomi note 13 pro plus'),
(' POCO X6 pro'),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Samsung A15'),
(' Infinix note 40 pro'),
(' Xiaomi note 13'),
(' Samsung A35'),
(' Infinix note 40'),
(' Xiaomi note 13 pro'),
(' Samsung S23 ultra'),
(' Infinix note 40 pro'),
(' Infinix zero 40'),
(' Xiaomi 13C'),
(' Iphone 12'),
(' Samsung A15'),
(' Red magic 9 pro'),
(' Infinix note 40 pro'),
(' Tecno Camon 20 pro'),
(' Infinix note 40 pro'),
(' Xiaomi note 13'),
(' Iphone 15'),
(' Infinix note 40'),
(' Samsung S23 fe'),
(' Infinix note 40 pro'),
(' Samsuns S21'),
(' Infinix zero 30'),
(' Tecno spark 20 pro'),
(' Xiaomi note 13 pro'),
(' Iphone 15 pro'),
(' Samsung S24 ultra'),
(' Samsung note 10 plus'),
(' Honor 90 GT'),
(' Realme 12 pro plus'),
(' Samsung A15'),
(' Xiaomi note 13'),
(' Tecno 30 pro'),
(' Infinix note 40 pro'),
(' Samsung A15'),
(' Tecno spark 20 pro plus'),
(' Camon 30'),
(' Infinix note 40 pro'),
(' Samsung A15'),
(' Xiaomi note 13'), 
(' Tecno pova 5 pro'),
(' Samsung S21 ultra'),
(' Xiaomi 13C'),
(' Infinix smart 7'),
(' Honor magic 6 lite'),
(' Tecno pova 5 pro'),
(' Samsung A15'),
(' Honor X6A'),
(' Infinix note 20i'),
(' Infinix note 40 pro'),
(' Tecno spark 20 pro plus'),
(' POCO X6 pro'),
(' Tecno spark 20'),
(' POCO F6 pro'),
(' POCO X6 pro'),
(' Honor X6a'),
(' POCO F6'),
(' POCO X5 pro'),
(' Samsung A25'),
(' Realme 12 pro plus'),
(' Samsung A15'),
(' Oneplus Ace 3'),
(' Honor X6a'),
(' Samsung A35'),
(' Tecno camon 20 pro'),
(' Samsung A15'),
(' Xiaomi 13C'),
(' Honor X6a '),
(' Samsung A15'),
(' Samsung A54'),
(' POCO f5 pro'),
(' Infinix note 30 pro'),
(' Xiaomi note 12'),
(' Honor 90 lite'),
(' Samsung S23 fe'),
(' POCO X6 pro'),
(' Huawei P60 pro'),
(' Samsung A14'),
(' Samsung S23 ultra'),
(' Samsung S24 ultra'),
(' Honor magic 5 lite '),
(' Honor X7b'),
(' Samsung A54'),
(' Samsung A34'),
(' Honor 90 '),
(' Tecno pova 5'),
(' Tecno pova 5'),
(' Samsung S23 fe'),
(' POCO X6 pro'),
(' Iphone 13'),
(' Iphone 15'),
(' Xiaomi note 11'),
(' POCO X6 pro'),
(' POCO X6 pro'),
(' Iphone 13'),
(' Xiaomi K40'),
(' POCO F5 pro'),
(' Xiaomi note 12 pro'), 
(' Samsung A54'),
(' OPPO reno 7'),
(' Cubot p80'),
(' POCO F5'),
(' POCO X5 pro'),
(' Motorola Edge 40 neo'),
(' Samsung S21 fe'),
(' Realme 12 pro plus'),
(' Xiaomi 13T'),
(' POCO X6 pro'),
(' Xiaomi note 13 pro'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi note 13 pro'),
(' Realme 12 pro plus'),
(' POCO X6 pro'),
(' Nothing 2A'),
(' Xiaomi note 13 pro'),
(' Xiaomi note 12'),
(' Nothing 2A'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi note 13 pro '),
(' Xiaomi 13T'),
(' POCO X6 pro'),
(' POCO F6'),
(' POCO F5 pro'),
(' POCO X6 pro'),
(' Oneplus Nord 3'),
(' POCO X6 pro'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi 13T'),
(' POCO X6 pro'),
(' POCO X3 pro'),
(' POCO X6 pro'),
(' Xiaomi 13T pro'),
(' Iphone 14 pro max'),
(' Honor 90'),
(' POCO F5 pro'),
(' Infinix note 40 pro'),
(' POCO F5 pro'),
(' Samsung S22 ultra'),
(' POCO F5 pro'),
(' Samsung S21 ultra'),
(' Iphone 14 pro'),
(' Realme c21'),
(' POCO X6 pro'),
(' POCO X6 pro'),
(' Realme 12 pro plus'),
(' Realme 12 pro plus'),
(' Realme 12 pro plus'),
(' POCO X6 pro'),
(' Realme 12 pro plus'),
(' Xiaomi note 13 pro'),
(' Realme 12 pro plus'),
(' Xiaomi note 13 pro '),
(' Realme 11 pro plus'),
(' Samsung S21 ultra'),
(' POCO X6 pro '),
(' Realme 12 pro plus'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi note 13 pro'),
(' Xiaomi note 13 pro'),
(' Infinity note 40 pro'),
(' POCO F6 pro'),
(' Samsung S21 fe'),
(' Google pixel 7 pro'),
(' Samsung S21 ultra'),
(' OPPO reno 11 '),
(' POCO X6 pro'),
(' Samsung S21 ultra'),
(' Xiaomi note 13 pro'),
(' Axon 50 lite'),
(' Xiaomi note 13 pro'),
(' POCO X6 pro'),
(' POCO X6 pro'),
(' POCO X6 pro'),
(' Xiaomi note 12'),
(' Xiaomi note 13 '),
(' Tecno spark 20 pro'),
(' POCO X6 pro'),
(' Samsung A21s'),
(' Samsung S23 '),
(' ZTE blade a54'),
(' Motorola G82'),
(' Tecno pova 5 pro'),
(' Samsung S20 fe'),
(' POCO F5'),
(' Xiaomi 13T'),
(' Tecno spark 20'),
(' POCO F5 '),
(' POCO F3'),
(' Oneplus 10t'),
(' Honor magic 5 lite'),
(' POCO F6'),
(' Tecno spark 20 pro plus'),
(' Motorola g53'),
(' Honor magic 6 lite'),
(' Iphone 15 pro max'),
(' Samsung s23 ultra'),
(' Samsung s24 ultra'),
(' Google pixel 8 pro'),
(' Oneplus 12'),
(' Oneplus 11'),
(' Honor magic 5 pro'),
(' Samsung s21 ultra'),
(' Samsung A55'),
(' Samsung s23 ultra'),
(' Samsung s24 ultra'),
(' Google pixel 8 pro'),
(' Huawei P60 pro'),
(' Samsung s23 ultra'),
(' Samsung s23 ultra'),
(' Redmagic 9 pro'),
(' Iphone 15 plus'),
(' Google pixel 8 pro'),
(' Iphone 15 plus'),
(' Iphone 15 pro'),
(' Realme GT neo 5'),
(' Iphone xr'),
(' Oneplus 11'),
(' Samsung s24 ultra'),
(' Iphone 15'),
(' Samsung s23 ultra'),
(' Iphone 15 pro'),
(' Iphone 15 plus'),
(' Honor 90'),
(' Samsung s21 fe'),
(' Iphone 15 plus'),
(' Iphone 14 pro max'),
(' Samsung s21 ultra'),
(' Samsung A55'),
(' Google pixel 8 pro'),
(' Samsung s21 plus'),
(' Iphone 15 plus'),
(' Iphone 14 pro max'),
(' Iphone 13 pro max'),
(' Google pixel 8 pro'),
(' Nothing A2'),
(' Redmagic 9 pro'),
(' Iphone 15 pro max'),
(' Iphone 15 plus'),
(' Samsung s23 ultra'),
(' Oneplus 12'),
(' OPPO A79'),
(' Samsung s24 ultra'),
(' Xiaomi 12'),
(' Xiaomi 13c'),
(' OPPO A79'),
(' Xiaomi note 10s'),
(' OPPO A53'),
(' OPPO A58'),
(' VIVO V30 lite'),
(' Realme note 50'),
(' Xiaomi 10c'),
(' Xiaomi note 8'),
(' Motorola G60'),
(' Xiaomi 13c'),
(' Motorola G54'),
(' Xiaomi note 13 pro plus'),
(' Xiaomi 13c'),
(' Xiaomi 13 pro'),
(' Samsung s24'),
(' Xiaomi 10'),
(' Redmagic 9'),
(' Xiaomi 13c'),
(' Nubia z60 ultra'),
(' Samsung s24 ultra'),
(' Redmagic 9 pro'),
(' Googel pixel 8 pro'),
(' Tecno pova 6'),
(' Samsung A02'),
(' Samsung s24'),
(' Nubia z60 ultra'),
(' Redmagic 9 pro'),
(' Iqoo neo 9'),
(' Iqoo 12'),
(' Iphone 15 pro max'),
(' Samsung s24 ultra'),
(' Huawei pura 70 ultra'),
(' Xiaomi 14 ultra'),
(' Nubia z60 ultra'),
(' Xiaomi k70 pro'),
(' Honor 200'),
(' Vivo x100s pro'),
(' Redmagic 9 pro'),
(' Samsung s24 ultra'),
(' Honor magic 6 pro'),
(' Samsung j6 neo'),
(' Iphone 15 pro max'),
(' Xiaomi k70'),
(' Nubia z60 ultra'),
(' Xiaomi 14 '),
(' iphone 15'),
(' Nothing 2A'),
(' Galaxy A55'),
(' POCO f6 '),
(' Iphone 12 pro max'),
(' Xiaomi note 10 pro'),
(' Google pixel 6 pro'),
(' POCO f5 pro'),
(' Xiaomi note 13 pro plus'),
(' Nothing A2'),
(' Oneplus 10t'),
(' Oneplus 12r'),
(' Samsung S23'),
(' POCO F6 pro'),
(' Xiaomi note 12'),
(' POCO m6 pro'),
(' POCO x6 '),
(' Samsung s23'),
(' Google pixel 8'),
(' Oneplus 10t'),
(' Google pixel 7A'),
(' Xiaomi pad 6 pro'),
(' Samsung s21 ultra'),
(' Samsung s10 plus'),
(' Nothin 2A'),
(' POCO x6 pro'),
(' Realme gt2'),
(' Samsung s21 ultra'),
(' Oneplus Ace 3'),
(' POCO f6 pro'),
(' Samsung s21 ultra'),
(' Xiaomi 12 pro'),
(' POCO x6 pro'),
(' Samsung note 20 ultra'),
(' Nothing 2A'),
(' Nothing 2A'),
(' Nothing 2A'),
(' Samsung A55'),
(' Xiaomi note 13 pro plus'), 
(' POCO F6 pro'),
(' POCO X6 pro'),
(' Xiaomi note 13 pro plus'), 
(' POCO F6 pro'),
(' Xiaomi 13T'),
(' Xiaomi note 13 pro plus'), 
(' Honor 90'),
(' Xiaomi note 13 pro plus'), 
(' Samsung s21 ultra'),
(' POCO x6 pro'),
(' Xiaomi note 12s'),   
(' Xiaomi note 13 pro plus'), 
(' Samsung s23 ultra'),
(' Xiaomi note 12 pro plus'),
(' Xiaomi 13T pro'),
(' Samsung note 10 plus'),
(' Xiaomi note 13 pro'),
(' Xiaomi note 13 pro plus'), 
(' Xiaomi note 13 pro plus '),
(' Xiaomi note 13 pro plus '),
(' Xiaomi note 13'),
(' Samsung A54'),
(' Xiaomi 13 pro'),
(' Xiaomi note 13 pro plus'), 
(' Iphone 13'),
(' Xiaomi note 13'),
(' Realme 12 pro plus'),
(' Xiaomi 13T'),
(' POCO X6 pro'),
(' Xiaomi note 13 pro plus'), 
(' Xiaomi note 13 pro '),
(' Xiaomi note 13 pro'), 
(' Realme 12 pro plus'),
(' Nothing 2A'),
(' Xiaomi 12'),
(' Xiaomi note 13 pro'), 
(' Xiaomi note 13 pro plus'), 
(' Nothing 2A'),
(' Xiaomi note 13 pro plus'), 
(' POCO F5 pro'),
(' POCO x6 pro'),
(' Xiaomi note 13 pro plus'), 
(' Xiaomi 13T'),
(' POCO x3 pro'),
(' POCO x6 pro'),
(' POCO x6 pro'),
(' Iphone 14 pro max'),
(' Xiaomi 13T pro'),
(' POCO F5 '),
(' Honor 90'),
(' Infinix note 40 pro'),
(' POCO f5'),
(' Samsung s22 ultra'),
(' POCO x6 pro'),
(' POCO f5 pro'),
(' Samsung S21 ultra'),
(' Iphone 14 pro'),
(' Realme c21'),
(' POCO x6 pro'),
(' POCO x6 pro'),
(' Realme 12 pro plus'),
(' Samsung A34'),
(' Xiaomi note 13 pro'), 
(' POCO x6 pro'),
(' Realme 12 pro plus'),
(' Realme 12 pro plus'),
(' Realme 12 pro plus'),
(' Infinix smart 8'),
(' Tecno spark 20'),
(' Redmi 13 c'),
(' Redmi 13 c'),
(' Infinix smart 8'),
(' Vivo y17s'),
(' Vivo y17s'),
(' Infinix smart 8'),
(' Tecno spark 20'),
(' Vivo y17s'),
(' Realme note 50'),
(' POCO m5'),
(' Vivo y17s'),
(' OPPO A17'),
(' Vivo y17s'),
(' Infinix smart 8'),
(' OPPO A18'),
(' Xiaomi 13c'),
(' Tecno spark 20'),
(' Infinix smart 8'),
(' Tecno spark 20'),
(' Vivo y17s'),
(' Tecno spark 20 pro'),
(' Infinix smart 8'),
(' Realme C15'),
(' Infinix smart 8'),
(' Xiaomi 12'),
(' Samsung A05'),
(' OPPO A18'),
(' Xiaomi 13c'),
(' Samsung A05'),
(' Infinix smart 8'),
(' Xiaomi 13c'),
(' Vivo y17s'),
(' Vivo y17s'),
(' Samsung A05'),
(' Vivo y17s'),
(' Tecno nova 5 pro'),
(' Infinix note 30 pro'),
(' Realme C51'),
(' Tecno spark 20'),
(' Xiaomi 13c'),
(' OPPO A18'),
(' Xiaomi 12'),
(' Xiaomi 14 ultra'),
(' Honor magic 6 pro'),
(' Huawei pura 70 ultra'),
(' Huawei pura 70 pro'),
(' Iphone 15 pro max'),
(' Samsung S24 ultra'),
(' Xiaomi 14 ultra'),
(' Samsung S24 ultra'),
(' Honor magic 6 pro'),
(' Iphone 15'),
(' Huawei pura 70 ultra'),
(' Xiaomi 14 ultra'),
(' Iphone 15 pro max'),
(' Iphone 16 pro max'),
(' Google pixel 8 pro'),
(' Honor magic 6 pro'),
(' Honor magic 6 pro'),
(' Iphone 15 pro max'),
(' Samsung S24 ultra'),
(' Iphone 15 pro max'),
(' Huawei pura 70 ultra'),
(' Iphone 15 pro max'),
(' Iphone 15 pro max'),
(' Xiaomi 14 ultra'),
(' Huawei pura 70 pro'),
(' Honor Magic 6 pro'),
(' Samsung S24 ultra'),
(' Huawei pura 70 '),
(' Samsung S24 ultra'),
(' Honor Magic 6 pro'),
(' Iphone 15 pro max'),
(' Honor Magic 6 pro'),
(' Huawei pura 70 ultra'),
(' Huawei Mate 60 Pro'),
(' Oppo X7 ultra'),
(' Vivo X100 Pro'),
(' Samsung S24 ultra'),
(' Huawei pura 70 ultra'),
(' Samsung s21 fe'),
(' Samsung s22 fe'),
(' Samsung s20'),
(' Samsung s10 plus'),
(' POCO X6 pro'),
(' Xiaomi note 13 pro plus'),
(' Samsung m35'),
(' Samsung s20 ultra'),
(' Samsung note 20 ultra'),
(' Samusng s23 fe'),
(' Iphone 13'),
(' Xiaomi 11T pro'),
(' Samsung s23 fe'),
(' Xiaomi mi 13'),
(' Xiaomi note 13 pro plus'),
(' POCO X6 pro'),
(' Samsung s20'),
(' Samsung A90'),
(' Samsung A54'),
(' Realme 12 pro plus'),
(' Tecno spark 20 pro plus'),
(' Samsung S21 ultra'),
(' Samsung A73'),
(' Samsung A35'),
(' Samsung s23'),
(' Motorola edge 40'),
(' Samsung A34'),
(' Xiaomi note 13 pro plus'),
(' Samsung A15'),
(' Honor magic 6 lite'),
(' Motorola edge 50 fusion'),
(' Samsung A34'),
(' Samsung S21'),
(' Samsung A35'),
(' Samsung A15'),
(' Tecno Spark 20 pro plus'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Tecno Spark 20 pro plus'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Infinix 40i'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Samsung A05s'),
(' Xiaomi 13c'),
(' Tecno spark 20 pro plus'),
(' Xiaomi 13c'),
(' Xiaomi 12'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Xiaomi note 13 pro'),
(' Xiaomi 13c'),
(' POCO F5'),
(' Honor magic 5 lite'),
(' Xiaomi note 13 pro'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Samsung S21 ultra'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Samsung A04s'),
(' Xiaomi 13c'),
(' Xiaomi note 9'),
(' Infinix note 40i'),
(' Xiaomi 13c'),
(' Infinix note 40i'),
(' Infinix note 40 pro'),
(' Xiaomi 13c'),
(' Xiaomi 13c'),
(' Infinix note 40i'),
(' Xiaomi 13c'),
(' Xiaomi note 13 pro'),
(' Infinix note 40 pro'),
(' Tecno spark 20 pro plus'),
(' Tecno spark 20 pro plus'),
(' Infinix note 40 pro'),
(' Honor magic 5 lite'),
(' Infinix note 40 pro'),
(' Honor magic 5 lite'),
(' Motorola Edge 40 neo'),
(' Infinix note 40 pro'),
(' Realme C67'),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Xiaomi note 13 pro '),
(' OPPO A38'),
(' Infinix note 40 pro'),
(' Infinix note 30'),
(' Infinix zero 40 '),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Xiaomi note 13 pro plus'),
(' Infinix note 40 pro'),
(' POCO M6 pro'),
(' Tecno spark 20 pro'),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Infinix note 40 pro'),
(' Samsung A25'),
(' Huawei mate 60 pro'),
(' VIVO X100 pro'),
(' Huawei pura 70 ultra'),
(' Samsung s24 ultra'),
(' Xiaomi 14 ultra'),
(' Huawei Pura 60 pro'),
(' Huawei Pura 70 pro'),
(' Xiaomi note 10s'),
(' Xiaomi 14 ultra'),
(' Samsung s23 ultra'),
(' Samsung s24 ultra'),
(' Samsung s24 ultra'),
(' Samsung s24'),
(' Xiaomi 14 ultra'),
(' Huawei pura 60 pro'),
(' Huawei mate 60'),
(' Iphone 13 pro '),
(' Iphone 14 plus'),
(' VIVO YT 22'),
(' Samsung s22'),
(' Huawei mate 10 pro'),
(' Huawei mate 60 '),
(' Huawei mate 60'),
(' Huawei pura 70 ultra'),
(' Iphone 15 pro max'),
(' Xiaomi mi 13 ultra '),
(' Huawei pura 70 ultra'),
(' Huawei mate 60 pro'),
(' Huawei P60 pro'),
(' Huawei P60 pro'),
(' Xiaomi 14 ultra'),
(' Xiaomi 14 ultra'),
(' Huawei P40 '),
(' Samsung A04e'), 	
(' VIVO X100 pro'),
(' Nubia z60 ultra'),
(' Phone 2A'),
(' POCO X6 pro'),
(' POCO F6 pro'),
(' POCO X6 pro'),
(' Xiaomi Note 13 pro'),
(' POCO X6 pro'),
(' Nubia z60 ultra'),
(' POCO F6 pro'),
(' POCO X6 pro'),
(' Nubia z60 ultra'),
(' Redmagic 9s pro'),
(' Nubia z60 ultra'),
(' POCO X3 pro'),
(' Motorola Edge 40 pro'),
(' Samsung s23 ultra'),
(' Infinix note 40 pro '),
(' Infinix gt 20 pro'),
(' Nubia z60'),
(' POCO F6 pro'),
(' POCO X6 pro');

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Samsung%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Xiaomi%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%POCO%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Huawei%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%VIVO%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Nubia%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Phone%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%OPPO%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Motorola%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Infinix%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Tecno%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Realme%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Honor%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Redmi%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%google%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%ZTE%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Oneplus%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Nothing%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Iqoo %';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Redmagic%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Cubot%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Camon%';
 
SELECT tel
FROM Telefonos
WHERE tel LIKE '%Infinity%';

SELECT tel
FROM Telefonos
WHERE tel LIKE '%Axon%';
